@startuml
set namespaceSeparator ::

class BitmapMetadata {
}

class Metadata {
+ int flags
+ int expire
+ int version
+ int size
+ void InitVersionCounter()
+ enum RedisType Type()
+ int TTL()
+ int Time()
+ _Bool Expired()
+ void Encode(int *dst)
+ rocksdb::Status Decode(const int & bytes)
+ _Bool operator==(const class Metadata & that)
}

class HashMetadata {
}

class InternalKey {
+ class rocksdb::Slice GetNamespace()
+ class rocksdb::Slice GetKey()
+ class rocksdb::Slice GetSubKey()
+ int GetVersion()
+ void Encode(int *out)
+ _Bool operator==(const class InternalKey & that)
}

class KeyNumStats {
+ int n_key
+ int n_expires
+ int n_expired
+ int avg_ttl
}

class ListMetadata {
+ int head
+ int tail
+ void Encode(int *dst)
+ rocksdb::Status Decode(const int & bytes)
}

class SetMetadata {
}

class SortedintMetadata {
}

class ZSetMetadata {
}

BitmapMetadata -up-|> Metadata
HashMetadata -up-|> Metadata
ListMetadata -up-|> Metadata
SetMetadata -up-|> Metadata
SortedintMetadata -up-|> Metadata
ZSetMetadata -up-|> Metadata
@enduml
